/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.StaffRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.PharmacyOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.PharmacyWorkRequest;
import EmailValidation.EmailValidator;
import EmailValidation.SendMail;
import Logging.LogReports;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Priyanka
 */
public class RequestToPharmacyJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private LabTestWorkRequest request;
     DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
Date date = new Date();

    /**
     * Creates new form RequestToPharmacyJPanel
     */

private BufferedImage image;

    LogReports staffLog = new LogReports();
   int count = 0;
   static int i = 0;
   SendMail mail = new SendMail();
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        g.drawImage(image, 0, 0,this.getWidth(), this.getHeight(), null); // see javadoc for more info on the parameters            
    }
    public RequestToPharmacyJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, LabTestWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.request = request;
        requestPharmacyBtn.setEnabled(false);
       
    loadData();
    
       try {                
          image = ImageIO.read(new File("F:\\staff1.jpg"));
       
       } catch (IOException ex) {
            // handle exception...
                    System.out.println("Exception:" + ex);
       }
       valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        prescriptionTxt = new javax.swing.JTextField();
        patientNameTxt = new javax.swing.JTextField();
        requestIDTxt = new javax.swing.JTextField();
        requestPharmacyBtn = new javax.swing.JButton();
        attachBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Send a request to the Pharmacy of ");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 330, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 130, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Prescription");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Patient's name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Request ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        prescriptionTxt.setEditable(false);
        prescriptionTxt.setEnabled(false);
        prescriptionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prescriptionTxtActionPerformed(evt);
            }
        });
        add(prescriptionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 240, -1));

        patientNameTxt.setEditable(false);
        patientNameTxt.setEnabled(false);
        patientNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientNameTxtActionPerformed(evt);
            }
        });
        add(patientNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 240, -1));

        requestIDTxt.setEditable(false);
        requestIDTxt.setEnabled(false);
        requestIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestIDTxtActionPerformed(evt);
            }
        });
        add(requestIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 240, -1));

        requestPharmacyBtn.setBackground(new java.awt.Color(0, 0, 0));
        requestPharmacyBtn.setForeground(new java.awt.Color(255, 255, 255));
        requestPharmacyBtn.setText("Request Pharmacy");
        requestPharmacyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestPharmacyBtnActionPerformed(evt);
            }
        });
        add(requestPharmacyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 260, 240, 30));

        attachBtn.setBackground(new java.awt.Color(0, 0, 0));
        attachBtn.setForeground(new java.awt.Color(255, 255, 255));
        attachBtn.setText("Attach");
        attachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachBtnActionPerformed(evt);
            }
        });
        add(attachBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        backBtn.setIcon(new javax.swing.ImageIcon("F:\\back.png")); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void requestIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestIDTxtActionPerformed

    private void patientNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientNameTxtActionPerformed

    private void requestPharmacyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestPharmacyBtnActionPerformed
        // TODO add your handling code here:
        
        if(prescriptionTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please attach the prescription");
            return;
        }
        
        final PharmacyWorkRequest phrequest = new PharmacyWorkRequest();
       
        
    switch (phrequest.getCountOfRequests()) {
        case 0:
            phrequest.setCountOfRequests();
            break;
        case 1:
            phrequest.setCountOfRequests();
            break;
        case 2:
            phrequest.setCountOfRequests();
            
            break;
        default:
            break;
    }
//        phrequest.setPrescriptionLocation(prescriptionTxt.getText());
//        phrequest.setPatientName(request.getPatientName());
//        phrequest.setRequestId(request.getRequestId());
//        phrequest.setSender(userAccount);
//        phrequest.setStatus("Sent");
//        phrequest.setRequestDate(date);
//         System.out.println("count of requests--"+phrequest.getCountOfRequests() );
//        Organization org = null;
//        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
//            if (organization instanceof PharmacyOrganization){
//                org = organization;
//                break;
//            }
//        }
//        if (org!=null){
//            org.getWorkQueuePharmacy().getWorkRequestPharmacyList().add(phrequest);
//            userAccount.getWorkQueuePharmacy().getWorkRequestPharmacyList().add(phrequest);
//        }
//        
              
      if(phrequest.getCountOfRequests() <= 3){
          
          phrequest.setPrescriptionLocation(prescriptionTxt.getText());
        phrequest.setPatientName(request.getPatientName());
        phrequest.setRequestId(request.getRequestId());
        phrequest.setSender(userAccount);
        phrequest.setStatus("Sent");
        phrequest.setRequestDate(date);
         System.out.println("count of requests--"+phrequest.getCountOfRequests() );
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof PharmacyOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueuePharmacy().getWorkRequestPharmacyList().add(phrequest);
            userAccount.getWorkQueuePharmacy().getWorkRequestPharmacyList().add(phrequest);
        }
        
           String data = "The employee with UserName: "+userAccount.getUsername()+
                    " sent a request to the pharmacy for: "+request.getPatientName()+
                    " with requestID:" + request.getRequestId() + " and the number of requests are: "+phrequest.getCountOfRequests();
            staffLog.logUserData(data, userAccount.getUsername());
//           
//            mail.sendAlertMail(data, "F:/Alerts/"+userAccount.getUsername()+"/"+userAccount.getUsername());
//           
      }else{
           new Thread(new Runnable() {
            public void run() {
                  String data = "The employee with UserName: "+userAccount.getUsername()+
                    " sent a request to the pharmacy for: "+request.getPatientName()+
                    " with requestID:" + request.getRequestId() + " and the number of requests are: "
                          +phrequest.getCountOfRequests();
            staffLog.logUserData(data, userAccount.getUsername());
         
        mail.sendAlertMail(data, "F:/Alerts/"+userAccount.getUsername()+"/"+userAccount.getUsername());            }
        }).start();
       
      }
      
            
       staffLog.logUserData("A request was sent to the pharmacy for patient: "+request.getPatientName()+" and RequestID: "+request.getRequestId(),
                userAccount.getUsername());
       requestPharmacyBtn.setEnabled(false);
    try {
        Thread.sleep(100);
    } catch (InterruptedException ex) {
        Logger.getLogger(RequestToPharmacyJPanel.class.getName()).log(Level.SEVERE, null, ex);
    }
//        if(phrequest.getCountOfRequests().equals(3)){
//            mail.sendAlertMail(data, "F:/"+userAccount.getUsername());
//            
//        }
        
requestPharmacyBtn.setEnabled(false);
        System.out.println("Pharmacy");
        
        
        

    }//GEN-LAST:event_requestPharmacyBtnActionPerformed

    private void attachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachBtnActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String fileName = f.getAbsolutePath();
        prescriptionTxt.setText(fileName);
        
         if(!prescriptionTxt.getText().isEmpty()){
            if(prescriptionTxt.getText().contains(request.getRequestId())){
                
            }else {
                JOptionPane.showMessageDialog(null, "Please re-check the file and name and attach the right prescription!");
                return;
            }
            requestPharmacyBtn.setEnabled(true);
            
        }
         if(!prescriptionTxt.getText().isEmpty()){
              if(prescriptionTxt.getText().contains("Alerts") || prescriptionTxt.getText().contains("db4o")){
                  mail.sendAlertMail("The user with UserName: " + userAccount.getUsername()+" is trying to access confidential data."
                          + "Please track the user. ", "F:/Alerts/"+userAccount.getUsername()+userAccount.getUsername());
              }
         }
    }//GEN-LAST:event_attachBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
           userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        StaffWorkAreaPanel dwjp = (StaffWorkAreaPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
     
        
        
        
    }//GEN-LAST:event_backBtnActionPerformed

    private void prescriptionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescriptionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prescriptionTxtActionPerformed

    
private void loadData(){
   // messageJTextField.setText(request.getMessage());
    patientNameTxt.setText(request.getPatientName());
    requestIDTxt.setText(request.getRequestId());
}
//    
//    
//    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
//    
//        String message = prescriptionTxt.getText();
//        String patientName = patientNameTxt.getText();
//        String random = requestIDTxt.getText();
//        
//        
//        PharmacyWorkRequest request = new PharmacyWorkRequest();
//        request.setPrescriptionLocation(message);
//        request.setPatientName(patientName);
//      //  request.setRequestId(String.valueOf(number));
//        request.setSender(userAccount);
//        request.setStatus("Sent");
//        
//        Organization org = null;
//        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
//            if (organization instanceof DoctorOrganization){
//                org = organization;
//                break;
//            }
//        }
//        if (org!=null){
//            org.getWorkQueuePharmacy().getWorkRequestPharmacyList().add(request);
//            userAccount.getWorkQueuePharmacy().getWorkRequestPharmacyList().add(request);
//        }
//    }
//    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attachBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField patientNameTxt;
    private javax.swing.JTextField prescriptionTxt;
    private javax.swing.JTextField requestIDTxt;
    private javax.swing.JButton requestPharmacyBtn;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
