/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Patient;

import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.PharmacyOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.PharmacyWorkRequest;
import Logging.LogReports;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Priyanka
 */
public class PatientRequestToPharmacyJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private LabTestWorkRequest request;
     DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
Date date = new Date();
LogReports patientLog = new LogReports();
    /**
     * Creates new form RequestToPharmacyJPanel
     */
    
    public PatientRequestToPharmacyJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, LabTestWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.request = request;
        requestPharmacyBtn.setEnabled(false);
       
    loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        prescriptionTxt = new javax.swing.JTextField();
        patientNameTxt = new javax.swing.JTextField();
        requestIDTxt = new javax.swing.JTextField();
        requestPharmacyBtn = new javax.swing.JButton();
        attachBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Send a request to the Pharmacy of ");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 330, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 12, 160, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Prescription");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Patient's name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Request ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        prescriptionTxt.setEditable(false);
        prescriptionTxt.setEnabled(false);
        prescriptionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prescriptionTxtActionPerformed(evt);
            }
        });
        add(prescriptionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 230, -1));

        patientNameTxt.setEditable(false);
        patientNameTxt.setEnabled(false);
        patientNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientNameTxtActionPerformed(evt);
            }
        });
        add(patientNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 230, -1));

        requestIDTxt.setEditable(false);
        requestIDTxt.setEnabled(false);
        requestIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestIDTxtActionPerformed(evt);
            }
        });
        add(requestIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 230, -1));

        requestPharmacyBtn.setBackground(new java.awt.Color(0, 0, 0));
        requestPharmacyBtn.setForeground(new java.awt.Color(255, 255, 255));
        requestPharmacyBtn.setText("Request Pharmacy");
        requestPharmacyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestPharmacyBtnActionPerformed(evt);
            }
        });
        add(requestPharmacyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 230, 30));

        attachBtn.setBackground(new java.awt.Color(0, 0, 0));
        attachBtn.setForeground(new java.awt.Color(255, 255, 255));
        attachBtn.setText("Attach");
        attachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachBtnActionPerformed(evt);
            }
        });
        add(attachBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 110, -1));

        backBtn.setIcon(new javax.swing.ImageIcon("F:\\back.png")); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void requestIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestIDTxtActionPerformed

    private void patientNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientNameTxtActionPerformed

    private void requestPharmacyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestPharmacyBtnActionPerformed
        // TODO add your handling code here:
        
        PharmacyWorkRequest phrequest = new PharmacyWorkRequest();
        phrequest.setPrescriptionLocation(prescriptionTxt.getText());
        phrequest.setPatientName(request.getPatientName());
        phrequest.setRequestId(request.getRequestId());
        phrequest.setSender(userAccount);
        phrequest.setStatus("Request sent to Pharmacy");
        phrequest.setRequestDate(date);
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof PharmacyOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueuePharmacy().getWorkRequestPharmacyList().add(phrequest);
            userAccount.getWorkQueuePharmacy().getWorkRequestPharmacyList().add(phrequest);
        }
        System.out.println("Pharmacy");
        patientLog.logUserData("A request was sent to the Pharmacy by the patient: "+request.getPatientName()+" with RequestID: "+request.getRequestId(),
                userAccount.getUsername());
       requestPharmacyBtn.setEnabled(false);

    }//GEN-LAST:event_requestPharmacyBtnActionPerformed

    private void attachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachBtnActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String fileName = f.getAbsolutePath();
        prescriptionTxt.setText(fileName);
        
        if(!prescriptionTxt.getText().isEmpty()){
            if(prescriptionTxt.getText().contains(request.getRequestId())){
                
            }else{
                JOptionPane.showMessageDialog(null, "Please re-check the file and name and attach the right prescription!");
                return;
            }
            requestPharmacyBtn.setEnabled(true);
            
        }
       
    }//GEN-LAST:event_attachBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
           userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PatientWorkAreaPanel dwjp = (PatientWorkAreaPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
     
        
        
        
    }//GEN-LAST:event_backBtnActionPerformed

    private void prescriptionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescriptionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prescriptionTxtActionPerformed

    
private void loadData(){
   // messageJTextField.setText(request.getMessage());
    patientNameTxt.setText(request.getPatientName());
    requestIDTxt.setText(request.getRequestId());
}
//    
//    
//    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
//    
//        String message = prescriptionTxt.getText();
//        String patientName = patientNameTxt.getText();
//        String random = requestIDTxt.getText();
//        
//        
//        PharmacyWorkRequest request = new PharmacyWorkRequest();
//        request.setPrescriptionLocation(message);
//        request.setPatientName(patientName);
//      //  request.setRequestId(String.valueOf(number));
//        request.setSender(userAccount);
//        request.setStatus("Sent");
//        
//        Organization org = null;
//        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
//            if (organization instanceof DoctorOrganization){
//                org = organization;
//                break;
//            }
//        }
//        if (org!=null){
//            org.getWorkQueuePharmacy().getWorkRequestPharmacyList().add(request);
//            userAccount.getWorkQueuePharmacy().getWorkRequestPharmacyList().add(request);
//        }
//    }
//    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attachBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField patientNameTxt;
    private javax.swing.JTextField prescriptionTxt;
    private javax.swing.JTextField requestIDTxt;
    private javax.swing.JButton requestPharmacyBtn;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
